from fastapi import FastAPI, Request, HTTPException, status
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from schemas import PostCreate, PostResponse


##
## We are focusing on the API endpoints 
## not the HTML rendering part, 
## so we will hide the home page and posts page from the API documentation
## **Pydantic validation is done on the schemas.py file**

app = FastAPI()
templates = Jinja2Templates(directory="templates")

posts: list[dict] = [
    {"id": 1, "title": "First Post", "content": "This is the content of the first post.", "author": "Alice", "date_posted": "2024-06-01"},
    {"id": 2, "title": "Second Post", "content": "This is the content of the second post.", "author": "Bob", "date_posted": "2024-06-02"},
    {"id": 3, "title": "Third Post", "content": "This is the content of the third post.", "author": "Charlie", "date_posted": "2024-06-03"}
]

@app.get("/api")
def home():
    return {"message": "Welcome to the FastAPI Blog!"}


# ## Home page and posts page
# ## hide these endpoints from the API documentation
# @app.get("/", response_class=HTMLResponse, include_in_schema=False)
# @app.get("/posts", response_class=HTMLResponse, include_in_schema=False)
# def home():
#     return f"<h1>{posts[0]['title']}</h1>"

## Using template response for home page and posts page
## Home page and posts page
## hide these endpoints from the API documentation
@app.get("/", include_in_schema=False)
@app.get("/posts",  include_in_schema=False)
def home(request: Request):
    return templates.TemplateResponse(request, "home.html", {"posts": posts})




## Get all posts
@app.get("/api/posts", response_model=list[PostResponse], status_code=status.HTTP_200_OK)
def get_posts():
    return posts

## Get specific post by id
@app.get("/api/posts/{post_id}", response_model=PostResponse)
def get_post(post_id: int):
    for post in posts:
        if post["id"] == post_id:
            return post
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Post not found")

## Create a new post
@app.post("/api/posts", response_model=PostResponse, status_code=status.HTTP_201_CREATED)
def create_post(post: PostCreate):
    max_id = max(post["id"] for post in posts) + 1 if posts else 1
    new_post = {
        "id": max_id,
        "title": post.title,
        "content": post.content,
        "author": post.author,
        "date_posted": "2024-06-04"  # This would typically be generated by the system
    }
    posts.append(new_post)
    return new_post